import { Button, Input, Space } from 'antd';
import React, { ChangeEvent, useEffect, useState } from 'react';
import LoginBg from './init.ts'
import styles from './index.module.scss'

const View = () => {
    // after the page is loaded, init the starry background
    useEffect(() => {
        const loginBg = new LoginBg();
        loginBg.init();
    }, []);

    // get user's input
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [captcha, setCaptcha] = useState('');

    // login
    const login = () => {
        console.log("username: " + username);
        console.log("password: " + password);
        console.log("captcha: " + captcha);
    }

    return (
        <div className={styles.page} >
            {/* starry background */}
            <canvas id="canvas" className={styles.canvas} style={{ backgroundColor: "#000" }}></canvas>

            {/* login form */}
            <div className={styles.loginBox}>
                {/* header */}
                <div className={styles.loginHeader}>
                    <div>
                        <h1>Management System</h1>
                    </div>
                </div>

                {/* form */}
                <div className={styles.loginBody}>
                    <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
                        <Input  placeholder='username' onChange={(e: ChangeEvent<HTMLInputElement>) => setUsername(e.target.value)}></Input>
                        <Input.Password placeholder='password' onChange={(e: ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}></Input.Password>
                        <div className={styles.captchaBox}>
                            <Input className={styles.captcha} placeholder='captcha' onChange={(e: ChangeEvent<HTMLInputElement>) => setCaptcha(e.target.value)}></Input>
                            {/* captcha's image is generated by backend */}
                            <img className={styles.captchaImg} src="https://picsum.photos/200/300" alt="captcha" />
                        </div>
                        <Button type="primary" className={styles.button} onClick={login}>Login</Button>
                    </Space>
                </div>
            </div>
        </div>
    );
}

export default View