import { Button, Input, Space, message } from 'antd';
import { ChangeEvent, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import LoginBg from './init'
import styles from './index.module.scss'
import { CaptchaApiGet, LoginApiPost } from '@/api/request'

const View = () => {
    // after the page is loaded, init the starry background
    useEffect(() => {
        // init starry background
        const loginBg = new LoginBg();
        loginBg.init();
        window.onresize = () => {
            loginBg.init();
        }

        // get captcha's image
        getCaptchaImg();
    }, []);

    // navigate
    const navigate = useNavigate();

    // get user's input
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [captcha, setCaptcha] = useState('');

    // captcha's image
    const [captchaImg, setCaptchaImg] = useState('');

    // get captcha's image
    // the image is generated by backend
    const getCaptchaImg = async () => {
        let res = await CaptchaApiGet();
        if (res.code === 200) {
            // render the image
            setCaptchaImg(res.img);
            // save uuid to local storage
            localStorage.setItem("captcha_uuid", res.uuid);
        }
    }

    // login
    const login = async () => {
        if (!username.trim() || !password.trim() || !captcha.trim()) {
            message.warning("Please fill in all the blanks");
            return;
        }

        let loginResult = await LoginApiPost({
            username: username,
            password: password,
            captcha: captcha,
            uuid: localStorage.getItem("captcha_uuid") as string
        })

        if (loginResult.code === 200) {
            // login success
            message.success("Login success");

            // save token to local storage
            localStorage.setItem("react_management_token", loginResult.token);

            // delete captcha's uuid
            localStorage.removeItem("captcha_uuid");

            // jump to home page
            navigate("/");

        }

    }

    return (
        <div className={styles.page} >
            {/* starry background */}
            <canvas id="canvas" className={styles.canvas} style={{ backgroundColor: "#000" }}></canvas>

            {/* login form */}
            <div className={styles.loginBox}>
                {/* header */}
                <div className={styles.loginHeader}>
                    <div>
                        <h1>Management System</h1>
                    </div>
                </div>

                {/* form */}
                <div className={styles.loginBody}>
                    <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
                        <Input placeholder='username' onChange={(e: ChangeEvent<HTMLInputElement>) => setUsername(e.target.value)}></Input>
                        <Input.Password placeholder='password' onChange={(e: ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}></Input.Password>
                        <div className={styles.captchaBox}>
                            <Input className={styles.captcha} placeholder='captcha' onChange={(e: ChangeEvent<HTMLInputElement>) => setCaptcha(e.target.value)}></Input>
                            {/* captcha's image is generated by backend */}
                            <div className={styles.captchaImg} onClick={getCaptchaImg}>
                                <img src={captchaImg} alt="captcha" />
                            </div>
                        </div>
                        <Button type="primary" className={styles.button} onClick={login}>Login</Button>
                    </Space>
                </div>
            </div>
        </div>
    );
}

export default View